// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0SdhW9GEjn5LcxfBzU_2sQt52a8cGMo',
    appId: '1:351738810212:web:4d397e228bd2af3691f471',
    messagingSenderId: '351738810212',
    projectId: 'challenge-as',
    authDomain: 'challenge-as.firebaseapp.com',
    databaseURL: 'https://challenge-as-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-as.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsBNkepj9D0s-sX8xStN4w8KqSRrW62g',
    appId: '1:351738810212:android:fa465120e76ca9ce91f471',
    messagingSenderId: '351738810212',
    projectId: 'challenge-as',
    databaseURL: 'https://challenge-as-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-as.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5WQc29SsCpTiC7RsYsIFOrlLgHMu1i4U',
    appId: '1:351738810212:ios:78045651a72fac7991f471',
    messagingSenderId: '351738810212',
    projectId: 'challenge-as',
    databaseURL: 'https://challenge-as-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-as.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5WQc29SsCpTiC7RsYsIFOrlLgHMu1i4U',
    appId: '1:351738810212:ios:78045651a72fac7991f471',
    messagingSenderId: '351738810212',
    projectId: 'challenge-as',
    databaseURL: 'https://challenge-as-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-as.appspot.com',
    iosBundleId: 'com.example.authApp',
  );
}
